import { create } from 'zustand';
import type { Template, Shape, Connector, TemplateCategory } from '../types';
import { generateId } from './canvasStore';

// Built-in templates
const builtInTemplates: Template[] = [
  {
    id: 'blank',
    name: 'Blank Canvas',
    description: 'Start with an empty canvas',
    category: 'custom',
    thumbnail: '📄',
    data: { shapes: [], connectors: [] },
    isBuiltIn: true,
  },
  {
    id: 'brainstorm-basic',
    name: 'Brainstorm Session',
    description: 'Central topic with branching ideas',
    category: 'brainstorm',
    thumbnail: '💡',
    data: {
      shapes: [
        {
          id: 'center',
          type: 'sticky',
          x: 400,
          y: 300,
          width: 150,
          height: 150,
          fill: '#FFE299',
          stroke: 'transparent',
          strokeWidth: 0,
          text: 'Main Topic',
          fontSize: 16,
          fontFamily: 'Arial',
          textColor: '#1a1a1a',
          stickyColor: 'yellow',
        },
        {
          id: 'idea1',
          type: 'sticky',
          x: 200,
          y: 150,
          width: 150,
          height: 150,
          fill: '#A8DAFF',
          stroke: 'transparent',
          strokeWidth: 0,
          text: 'Idea 1',
          fontSize: 14,
          fontFamily: 'Arial',
          textColor: '#1a1a1a',
          stickyColor: 'blue',
        },
        {
          id: 'idea2',
          type: 'sticky',
          x: 600,
          y: 150,
          width: 150,
          height: 150,
          fill: '#B3EFBD',
          stroke: 'transparent',
          strokeWidth: 0,
          text: 'Idea 2',
          fontSize: 14,
          fontFamily: 'Arial',
          textColor: '#1a1a1a',
          stickyColor: 'green',
        },
        {
          id: 'idea3',
          type: 'sticky',
          x: 200,
          y: 450,
          width: 150,
          height: 150,
          fill: '#FFA8DB',
          stroke: 'transparent',
          strokeWidth: 0,
          text: 'Idea 3',
          fontSize: 14,
          fontFamily: 'Arial',
          textColor: '#1a1a1a',
          stickyColor: 'pink',
        },
        {
          id: 'idea4',
          type: 'sticky',
          x: 600,
          y: 450,
          width: 150,
          height: 150,
          fill: '#D3BDFF',
          stroke: 'transparent',
          strokeWidth: 0,
          text: 'Idea 4',
          fontSize: 14,
          fontFamily: 'Arial',
          textColor: '#1a1a1a',
          stickyColor: 'violet',
        },
      ] as Shape[],
      connectors: [],
    },
    isBuiltIn: true,
  },
  {
    id: 'meeting-agenda',
    name: 'Meeting Agenda',
    description: 'Structured meeting with sections',
    category: 'meeting',
    thumbnail: '📋',
    data: {
      shapes: [
        {
          id: 'header',
          type: 'text',
          x: 100,
          y: 50,
          width: 400,
          height: 40,
          fill: 'transparent',
          stroke: 'transparent',
          strokeWidth: 0,
          text: 'Team Meeting Agenda',
          fontSize: 24,
          fontFamily: 'Arial',
          textColor: '#1f2937',
        },
        {
          id: 'section1',
          type: 'section',
          x: 100,
          y: 120,
          width: 250,
          height: 200,
          fill: '#dbeafe',
          stroke: '#93c5fd',
          strokeWidth: 1,
          cornerRadius: 8,
          sectionColor: 'blue',
          sectionTitle: 'Updates',
        },
        {
          id: 'section2',
          type: 'section',
          x: 380,
          y: 120,
          width: 250,
          height: 200,
          fill: '#dcfce7',
          stroke: '#86efac',
          strokeWidth: 1,
          cornerRadius: 8,
          sectionColor: 'green',
          sectionTitle: 'Discussion',
        },
        {
          id: 'section3',
          type: 'section',
          x: 100,
          y: 350,
          width: 530,
          height: 150,
          fill: '#fef9c3',
          stroke: '#fde047',
          strokeWidth: 1,
          cornerRadius: 8,
          sectionColor: 'yellow',
          sectionTitle: 'Action Items',
        },
      ] as Shape[],
      connectors: [],
    },
    isBuiltIn: true,
  },
  {
    id: 'retro-basic',
    name: 'Retrospective',
    description: 'What went well, what to improve, action items',
    category: 'retro',
    thumbnail: '🔄',
    data: {
      shapes: [
        {
          id: 'went-well',
          type: 'section',
          x: 50,
          y: 100,
          width: 280,
          height: 400,
          fill: '#dcfce7',
          stroke: '#86efac',
          strokeWidth: 1,
          cornerRadius: 8,
          sectionColor: 'green',
          sectionTitle: 'What Went Well',
        },
        {
          id: 'improve',
          type: 'section',
          x: 360,
          y: 100,
          width: 280,
          height: 400,
          fill: '#fee2e2',
          stroke: '#fca5a5',
          strokeWidth: 1,
          cornerRadius: 8,
          sectionColor: 'red',
          sectionTitle: 'What to Improve',
        },
        {
          id: 'actions',
          type: 'section',
          x: 670,
          y: 100,
          width: 280,
          height: 400,
          fill: '#dbeafe',
          stroke: '#93c5fd',
          strokeWidth: 1,
          cornerRadius: 8,
          sectionColor: 'blue',
          sectionTitle: 'Action Items',
        },
      ] as Shape[],
      connectors: [],
    },
    isBuiltIn: true,
  },
  {
    id: 'flowchart-basic',
    name: 'Basic Flowchart',
    description: 'Start, process, decision, end',
    category: 'flowchart',
    thumbnail: '🔀',
    data: {
      shapes: [
        {
          id: 'start',
          type: 'ellipse',
          x: 350,
          y: 50,
          width: 100,
          height: 50,
          fill: '#86efac',
          stroke: '#22c55e',
          strokeWidth: 2,
          text: 'Start',
          fontSize: 14,
          textColor: '#166534',
        },
        {
          id: 'process1',
          type: 'rectangle',
          x: 325,
          y: 150,
          width: 150,
          height: 60,
          fill: '#ffffff',
          stroke: '#1e1e1e',
          strokeWidth: 2,
          text: 'Process 1',
          fontSize: 14,
          textColor: '#1e1e1e',
        },
        {
          id: 'decision',
          type: 'diamond',
          x: 325,
          y: 260,
          width: 150,
          height: 100,
          fill: '#fef08a',
          stroke: '#eab308',
          strokeWidth: 2,
          text: 'Decision?',
          fontSize: 14,
          textColor: '#854d0e',
        },
        {
          id: 'process2',
          type: 'rectangle',
          x: 150,
          y: 410,
          width: 150,
          height: 60,
          fill: '#ffffff',
          stroke: '#1e1e1e',
          strokeWidth: 2,
          text: 'Process 2A',
          fontSize: 14,
          textColor: '#1e1e1e',
        },
        {
          id: 'process3',
          type: 'rectangle',
          x: 500,
          y: 410,
          width: 150,
          height: 60,
          fill: '#ffffff',
          stroke: '#1e1e1e',
          strokeWidth: 2,
          text: 'Process 2B',
          fontSize: 14,
          textColor: '#1e1e1e',
        },
        {
          id: 'end',
          type: 'ellipse',
          x: 350,
          y: 520,
          width: 100,
          height: 50,
          fill: '#fca5a5',
          stroke: '#ef4444',
          strokeWidth: 2,
          text: 'End',
          fontSize: 14,
          textColor: '#991b1b',
        },
      ] as Shape[],
      connectors: [
        {
          id: 'conn1',
          fromShapeId: 'start',
          toShapeId: 'process1',
          stroke: '#1e1e1e',
          strokeWidth: 2,
          arrow: true,
          arrowEnd: 'arrow',
          routing: 'straight',
        },
        {
          id: 'conn2',
          fromShapeId: 'process1',
          toShapeId: 'decision',
          stroke: '#1e1e1e',
          strokeWidth: 2,
          arrow: true,
          arrowEnd: 'arrow',
          routing: 'straight',
        },
        {
          id: 'conn3',
          fromShapeId: 'decision',
          toShapeId: 'process2',
          stroke: '#1e1e1e',
          strokeWidth: 2,
          arrow: true,
          arrowEnd: 'arrow',
          routing: 'orthogonal',
          label: 'Yes',
        },
        {
          id: 'conn4',
          fromShapeId: 'decision',
          toShapeId: 'process3',
          stroke: '#1e1e1e',
          strokeWidth: 2,
          arrow: true,
          arrowEnd: 'arrow',
          routing: 'orthogonal',
          label: 'No',
        },
        {
          id: 'conn5',
          fromShapeId: 'process2',
          toShapeId: 'end',
          stroke: '#1e1e1e',
          strokeWidth: 2,
          arrow: true,
          arrowEnd: 'arrow',
          routing: 'orthogonal',
        },
        {
          id: 'conn6',
          fromShapeId: 'process3',
          toShapeId: 'end',
          stroke: '#1e1e1e',
          strokeWidth: 2,
          arrow: true,
          arrowEnd: 'arrow',
          routing: 'orthogonal',
        },
      ] as Connector[],
    },
    isBuiltIn: true,
  },
  {
    id: 'planning-kanban',
    name: 'Kanban Board',
    description: 'To Do, In Progress, Done columns',
    category: 'planning',
    thumbnail: '📊',
    data: {
      shapes: [
        {
          id: 'todo',
          type: 'section',
          x: 50,
          y: 100,
          width: 280,
          height: 450,
          fill: '#f3f4f6',
          stroke: '#d1d5db',
          strokeWidth: 1,
          cornerRadius: 8,
          sectionColor: 'gray',
          sectionTitle: 'To Do',
        },
        {
          id: 'inprogress',
          type: 'section',
          x: 360,
          y: 100,
          width: 280,
          height: 450,
          fill: '#dbeafe',
          stroke: '#93c5fd',
          strokeWidth: 1,
          cornerRadius: 8,
          sectionColor: 'blue',
          sectionTitle: 'In Progress',
        },
        {
          id: 'done',
          type: 'section',
          x: 670,
          y: 100,
          width: 280,
          height: 450,
          fill: '#dcfce7',
          stroke: '#86efac',
          strokeWidth: 1,
          cornerRadius: 8,
          sectionColor: 'green',
          sectionTitle: 'Done',
        },
        {
          id: 'task1',
          type: 'sticky',
          x: 80,
          y: 150,
          width: 220,
          height: 80,
          fill: '#FFE299',
          stroke: 'transparent',
          strokeWidth: 0,
          text: 'Task 1',
          fontSize: 14,
          fontFamily: 'Arial',
          textColor: '#1a1a1a',
          stickyColor: 'yellow',
        },
        {
          id: 'task2',
          type: 'sticky',
          x: 80,
          y: 250,
          width: 220,
          height: 80,
          fill: '#FFE299',
          stroke: 'transparent',
          strokeWidth: 0,
          text: 'Task 2',
          fontSize: 14,
          fontFamily: 'Arial',
          textColor: '#1a1a1a',
          stickyColor: 'yellow',
        },
      ] as Shape[],
      connectors: [],
    },
    isBuiltIn: true,
  },
];

interface TemplateState {
  templates: Template[];
  customTemplates: Template[];
  selectedCategory: TemplateCategory | 'all';

  // Actions
  getTemplatesByCategory: (category: TemplateCategory | 'all') => Template[];
  getTemplateById: (id: string) => Template | undefined;
  addCustomTemplate: (template: Omit<Template, 'id' | 'isBuiltIn'>) => Template;
  removeCustomTemplate: (id: string) => void;
  setSelectedCategory: (category: TemplateCategory | 'all') => void;
}

export const useTemplateStore = create<TemplateState>((set, get) => ({
  templates: builtInTemplates,
  customTemplates: [],
  selectedCategory: 'all',

  getTemplatesByCategory: (category) => {
    const { templates, customTemplates } = get();
    const allTemplates = [...templates, ...customTemplates];
    if (category === 'all') return allTemplates;
    return allTemplates.filter((t) => t.category === category);
  },

  getTemplateById: (id) => {
    const { templates, customTemplates } = get();
    return [...templates, ...customTemplates].find((t) => t.id === id);
  },

  addCustomTemplate: (template) => {
    const newTemplate: Template = {
      ...template,
      id: `custom-${generateId()}`,
      isBuiltIn: false,
    };
    set((state) => ({
      customTemplates: [...state.customTemplates, newTemplate],
    }));
    return newTemplate;
  },

  removeCustomTemplate: (id) => {
    set((state) => ({
      customTemplates: state.customTemplates.filter((t) => t.id !== id),
    }));
  },

  setSelectedCategory: (category) => {
    set({ selectedCategory: category });
  },
}));

// Export built-in templates for direct access
export { builtInTemplates };
